<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>fsm</artifactId>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <forceJavacCompilerUse>true</forceJavacCompilerUse>
          <release>17</release>
          <source>17</source>
          <target>17</target>
        </configuration>
        <dependencies>
          <dependency>
            <artifactId>asm</artifactId>
            <groupId>org.ow2.asm</groupId>
            <version>9.8</version>
          </dependency>
        </dependencies>
        <groupId>org.apache.maven.plugins</groupId>
        <version>${maven-compiler-plugin.version}</version>
      </plugin>

      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>test</goal>
            </goals>
            <id>test</id>
            <phase>test</phase>
          </execution>
        </executions>
        <version>${maven-surefire-plugin.version}</version>
      </plugin>

      <plugin>
        <artifactId>findbugs-maven-plugin</artifactId>
        <groupId>org.codehaus.mojo</groupId>
        <version>${findbugs-maven-plugin.version}</version>
      </plugin>

      <plugin>
        <artifactId>maven-source-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>jar</goal>
            </goals>
            <id>attach-sources</id>
          </execution>
        </executions>
        <groupId>org.apache.maven.plugins</groupId>
        <version>${maven-source-plugin.version}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>${maven-javadoc-plugin.version}</version>
        <configuration>
          <doclint>all,-missing</doclint>
        </configuration>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.fasterxml.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>${jackson.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${junit.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <artifactId>slf4j-api</artifactId>
      <groupId>org.slf4j</groupId>
      <scope>compile</scope>
      <version>${sl4j.version}</version>
    </dependency>

    <dependency>
      <artifactId>lombok</artifactId>
      <groupId>org.projectlombok</groupId>
      <scope>compile</scope>
      <version>${lombok.version}</version>
    </dependency>

    <dependency>
      <artifactId>guava</artifactId>
      <groupId>com.google.guava</groupId>
      <scope>provided</scope>
      <version>${guava.version}</version>
    </dependency>

    <dependency>
      <artifactId>jackson-annotations</artifactId>
      <groupId>com.fasterxml.jackson.core</groupId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <artifactId>jackson-databind</artifactId>
      <groupId>com.fasterxml.jackson.core</groupId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <artifactId>jakarta.validation-api</artifactId>
      <groupId>jakarta.validation</groupId>
      <scope>compile</scope>
      <version>${jakarta.validation-api.version}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>junit-jupiter</artifactId>
      <groupId>org.junit.jupiter</groupId>
      <scope>test</scope>
      <version>${junit.version}</version>
    </dependency>
  </dependencies>

  <description>A simple quick to use fsm</description>
  <developers>
    <developer>
      <email>rkoushik.14@gmail.com</email>
      <id>koushikr</id>
      <name>Koushik Ramachandra</name>
    </developer>
  </developers>
  <distributionManagement>
    <repository>
      <id>ossrh</id>
      <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
    </repository>
    <snapshotRepository>
      <id>ossrh</id>
      <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
    </snapshotRepository>
  </distributionManagement>

  <groupId>com.grookage.fsm</groupId>
  <inceptionYear>2015</inceptionYear>
  <issueManagement>
    <system>GitHub Issues</system>
    <url>https://github.com/grookage/easy-fsm/issues</url>
  </issueManagement>
  <licenses>
    <license>
      <comments>A business-friendly OSS license</comments>
      <distribution>repo</distribution>
      <name>The Apache Software License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <modelVersion>4.0.0</modelVersion>
  <name>Easy fsm</name>
  <profiles>
    <profile>
      <activation>
        <property>
          <name>release</name>
          <value>true</value>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <artifactId>nexus-staging-maven-plugin</artifactId>
            <configuration>
              <autoReleaseAfterClose>true</autoReleaseAfterClose>
              <nexusUrl>https://s01.oss.sonatype.org/</nexusUrl>
              <serverId>ossrh</serverId>
            </configuration>
            <extensions>true</extensions>
            <groupId>org.sonatype.plugins</groupId>
            <version>${nexus-staging-maven-plugin.version}</version>
          </plugin>
          <plugin>
            <artifactId>maven-gpg-plugin</artifactId>
            <executions>
              <execution>
                <configuration>
                  <executable>gpg</executable>
                  <useAgent>true</useAgent>
                </configuration>
                <goals>
                  <goal>sign</goal>
                </goals>
                <id>sign-artifacts</id>
                <phase>verify</phase>
              </execution>
            </executions>
            <groupId>org.apache.maven.plugins</groupId>
            <version>${maven-gpg-plugin.version}</version>
          </plugin>
          <plugin>
            <artifactId>maven-enforcer-plugin</artifactId>
            <executions>
              <execution>
                <configuration>
                  <fail>true</fail>
                  <rules>
                    <requireReleaseDeps>
                      <message>No Snapshots Allowed!</message>
                    </requireReleaseDeps>
                  </rules>
                </configuration>
                <goals>
                  <goal>enforce</goal>
                </goals>
                <id>enforce-no-snapshots</id>
              </execution>
            </executions>
            <groupId>org.apache.maven.plugins</groupId>
            <version>${maven-enforcer-plugin.version}</version>
          </plugin>
          <plugin>
            <artifactId>maven-release-plugin</artifactId>
            <configuration>
              <autoVersionSubmodules>true</autoVersionSubmodules>
              <goals>deploy</goals>
              <releaseProfiles>release</releaseProfiles>
              <useReleaseProfile>false</useReleaseProfile>
            </configuration>
            <groupId>org.apache.maven.plugins</groupId>
            <version>${maven-release-plugin.version}</version>
          </plugin>
        </plugins>
      </build>
      <id>release</id>
    </profile>
  </profiles>

  <properties>
    <guava.version>33.5.0-jre</guava.version>
    <jackson.version>2.20.0</jackson.version>
    <lombok.version>1.18.42</lombok.version>
    <sl4j.version>1.7.36</sl4j.version>
    <sonar.coverage.exclusions>
      **com/grookage/fsm/**
    </sonar.coverage.exclusions>
    <sonar.host.url>https://sonarcloud.io</sonar.host.url>
    <sonar.organization>grookage</sonar.organization>
    <maven-release-plugin.version>3.1.1</maven-release-plugin.version>
    <maven-enforcer-plugin.version>3.6.1</maven-enforcer-plugin.version>
    <maven-gpg-plugin.version>3.2.8</maven-gpg-plugin.version>
    <nexus-staging-maven-plugin.version>1.7.0</nexus-staging-maven-plugin.version>
    <findbugs-maven-plugin.version>3.0.3</findbugs-maven-plugin.version>
    <maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>
    <maven-surefire-plugin.version>3.5.4</maven-surefire-plugin.version>
    <maven-source-plugin.version>3.3.1</maven-source-plugin.version>
    <maven-javadoc-plugin.version>3.12.0</maven-javadoc-plugin.version>
    <jakarta.validation-api.version>2.0.2</jakarta.validation-api.version>
    <junit.version>5.14.0</junit.version>
  </properties>

  <scm>
    <connection>scm:git:https://github.com/grookage/easy-fsm.git</connection>
    <developerConnection>scm:git:https://github.com/grookage/easy-fsm.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/grookage/easy-fsm.git</url>
  </scm>

  <url>https://github.com/grookage/easy-fsm</url>

  <version>2.0.4</version>
</project>
